import json

nb_path = r'd:\日常\@课程\科研\高维稀疏\JMLR-2023 U-statistics\U_stat_ADMM\exp1_plot_ranking.ipynb'

with open(nb_path, 'r', encoding='utf-8') as f:
    nb = json.load(f)

# 保留 cell[0] markdown 和 cell[1] 原始分析代码，替换 cell[2] 之后
nb['cells'] = nb['cells'][:2]

PLOT_SOURCE = [
    "# =============================================================\n",
    "# 跨实验条件 RMSE 折线图\n",
    "#\n",
    "# 图1: 噪声影响 — 4种 (m,n,pc) 场景 (2×2)\n",
    "# 图2: m / n / pc 影响 — 3行(噪声) × 3列(变量) 共9子图\n",
    "#   每行 = 一种噪声 (normal / exp / t1)\n",
    "#   每列 = 一个变量 (m 影响 | n 影响 | pc 影响)\n",
    "# =============================================================\n",
    "import json, glob, os\n",
    "import numpy as np\n",
    "import matplotlib.pyplot as plt\n",
    "\n",
    "RANKING_DIR  = 'ranking'\n",
    "ALGORITHMS   = ['Global', 'U-ADMM', 'D-ProxGD', 'Avg', 'Local']\n",
    "ALG_COLORS   = {'Global':'#F39C12', 'U-ADMM':'#2980B9',\n",
    "                 'D-ProxGD':'#8E44AD', 'Avg':'#E74C3C', 'Local':'#27AE60'}\n",
    "ALG_MARKERS  = {'Global':'o', 'U-ADMM':'s', 'D-ProxGD':'^', 'Avg':'D', 'Local':'v'}\n",
    "NOISES       = ['normal', 'exp', 't1']\n",
    "NOISE_LABELS = {'normal':'Normal', 'exp':'Exponential', 't1':'Student-t(1)'}\n",
    "\n",
    "\n",
    "# ---------- 数据加载 ----------\n",
    "def load_all(d):\n",
    "    records = []\n",
    "    for path in sorted(glob.glob(os.path.join(d, '*.json'))):\n",
    "        with open(path, 'r', encoding='utf-8') as fp:\n",
    "            data = json.load(fp)\n",
    "        p, res = data['parameters'], data['results']\n",
    "        rmses = {}\n",
    "        for alg in ALGORITHMS:\n",
    "            if alg in res[0] and isinstance(res[0][alg], dict):\n",
    "                vals = [r[alg]['RMSE'] for r in res\n",
    "                        if isinstance(r.get(alg), dict) and 'RMSE' in r[alg]]\n",
    "                if vals:\n",
    "                    rmses[alg] = float(np.mean(vals))\n",
    "        records.append({'params': p, 'rmses': rmses})\n",
    "    return records\n",
    "\n",
    "\n",
    "def filt(records, **conds):\n",
    "    out = []\n",
    "    for e in records:\n",
    "        p, ok = e['params'], True\n",
    "        for k, v in conds.items():\n",
    "            pv = p.get(k)\n",
    "            if pv is None: ok = False; break\n",
    "            ok = (abs(float(pv)-v)<=1e-9) if isinstance(v,float) else (pv==v)\n",
    "            if not ok: break\n",
    "        if ok: out.append(e)\n",
    "    return out\n",
    "\n",
    "\n",
    "# ---------- 绘图工具 ----------\n",
    "def annotate(ax, xs, ys, color):\n",
    "    for x, y in zip(xs, ys):\n",
    "        if not np.isnan(y):\n",
    "            ax.annotate(f'{y:.4f}', xy=(x, y), xytext=(0, 7),\n",
    "                        textcoords='offset points', ha='center', va='bottom',\n",
    "                        fontsize=6, color=color, fontweight='bold')\n",
    "\n",
    "\n",
    "def draw_lines(ax, entries):\n",
    "    xpos = list(range(len(entries)))\n",
    "    for alg in ALGORITHMS:\n",
    "        y  = [e['rmses'].get(alg, np.nan) for e in entries]\n",
    "        vx = [xi for xi, yi in zip(xpos, y) if not np.isnan(yi)]\n",
    "        vy = [yi for yi in y           if not np.isnan(yi)]\n",
    "        if not vx: continue\n",
    "        ax.plot(vx, vy, marker=ALG_MARKERS[alg], color=ALG_COLORS[alg],\n",
    "                label=alg, linewidth=1.8, markersize=6)\n",
    "        annotate(ax, vx, vy, ALG_COLORS[alg])\n",
    "\n",
    "\n",
    "def style(ax, xlabels, xlabel, title, show_legend=True):\n",
    "    ax.set_xticks(range(len(xlabels)))\n",
    "    ax.set_xticklabels(xlabels, fontsize=9)\n",
    "    ax.set_xlabel(xlabel, fontsize=9)\n",
    "    ax.set_ylabel('Mean RMSE', fontsize=9)\n",
    "    ax.set_title(title, fontsize=10, fontweight='bold')\n",
    "    ax.grid(True, alpha=0.3)\n",
    "    if show_legend:\n",
    "        ax.legend(fontsize=7)\n",
    "\n",
    "\n",
    "all_data = load_all(RANKING_DIR)\n",
    "print(f'Loaded {len(all_data)} experiment files.')\n",
    "\n",
    "\n",
    "# =============================================================\n",
    "# 图1: 噪声影响 — 4 种 (m,n,pc) 场景 (2×2 子图)\n",
    "# =============================================================\n",
    "SCENARIOS = [\n",
    "    {'m':10, 'n':100, 'pc':0.3},\n",
    "    {'m':10, 'n':100, 'pc':0.5},\n",
    "    {'m':20, 'n':100, 'pc':0.3},\n",
    "    {'m':10, 'n':50,  'pc':0.3},\n",
    "]\n",
    "\n",
    "fig1, axes1 = plt.subplots(2, 2, figsize=(13, 8))\n",
    "axes1 = axes1.flatten()\n",
    "\n",
    "for idx, sc in enumerate(SCENARIOS):\n",
    "    ax = axes1[idx]\n",
    "    entries = []\n",
    "    for noise in NOISES:\n",
    "        found = filt(all_data, noise_type=noise, **sc)\n",
    "        if found: entries.append(found[0])\n",
    "    entries = sorted(entries, key=lambda e: NOISES.index(e['params']['noise_type']))\n",
    "    draw_lines(ax, entries)\n",
    "    style(ax,\n",
    "          [NOISE_LABELS[e['params']['noise_type']] for e in entries],\n",
    "          'Noise Type',\n",
    "          f\"m={sc['m']}, n={sc['n']}, pc={sc['pc']}\")\n",
    "\n",
    "fig1.suptitle('Effect of Noise Type on Final RMSE', fontsize=13, fontweight='bold', y=1.01)\n",
    "plt.tight_layout()\n",
    "plt.savefig('rmse_noise_effect.pdf', bbox_inches='tight')\n",
    "plt.show()\n",
    "\n",
    "\n",
    "# =============================================================\n",
    "# 图2: 3行(噪声) × 3列(变量) — m / n / pc 影响\n",
    "#\n",
    "#         col0: m 影响      col1: n 影响      col2: pc 影响\n",
    "# row0  normal  [RMSE vs m] [RMSE vs n] [RMSE vs pc]\n",
    "# row1  exp     [RMSE vs m] [RMSE vs n] [RMSE vs pc]\n",
    "# row2  t1      [RMSE vs m] [RMSE vs n] [RMSE vs pc]\n",
    "# =============================================================\n",
    "fig2, axes2 = plt.subplots(3, 3, figsize=(15, 12))\n",
    "\n",
    "for ri, noise in enumerate(NOISES):\n",
    "    noise_label = NOISE_LABELS[noise]\n",
    "\n",
    "    # --- 列0: m 的影响 (n=100, pc=0.3) ---\n",
    "    ax = axes2[ri, 0]\n",
    "    entries = sorted(\n",
    "        [e for m in [10, 20] for e in filt(all_data, noise_type=noise, m=m, n=100, pc=0.3)],\n",
    "        key=lambda e: e['params']['m']\n",
    "    )\n",
    "    draw_lines(ax, entries)\n",
    "    style(ax, [str(e['params']['m']) for e in entries],\n",
    "          'm (# Nodes)',\n",
    "          f'{noise_label} | m effect\\n(n=100, pc=0.3)')\n",
    "\n",
    "    # --- 列1: n 的影响 (m=10, pc=0.3) ---\n",
    "    ax = axes2[ri, 1]\n",
    "    entries = []\n",
    "    for n in [50, 100]:\n",
    "        found = filt(all_data, noise_type=noise, m=10, n=n, pc=0.3)\n",
    "        if found: entries.append(found[0])\n",
    "    entries = sorted(entries, key=lambda e: e['params']['n'])\n",
    "    draw_lines(ax, entries)\n",
    "    style(ax, [str(e['params']['n']) for e in entries],\n",
    "          'n (Samples/Node)',\n",
    "          f'{noise_label} | n effect\\n(m=10, pc=0.3)',\n",
    "          show_legend=False)\n",
    "\n",
    "    # --- 列2: pc 的影响 (m=10, n=100) ---\n",
    "    ax = axes2[ri, 2]\n",
    "    entries = []\n",
    "    for pc in [0.3, 0.5]:\n",
    "        found = filt(all_data, noise_type=noise, m=10, n=100, pc=pc)\n",
    "        if found: entries.append(found[0])\n",
    "    entries = sorted(entries, key=lambda e: e['params']['pc'])\n",
    "    draw_lines(ax, entries)\n",
    "    style(ax, [str(e['params']['pc']) for e in entries],\n",
    "          'pc (Edge Prob.)',\n",
    "          f'{noise_label} | pc effect\\n(m=10, n=100)',\n",
    "          show_legend=False)\n",
    "\n",
    "fig2.suptitle('Effects of m / n / pc on Final RMSE (rows = noise type)',\n",
    "              fontsize=13, fontweight='bold')\n",
    "plt.tight_layout()\n",
    "plt.savefig('rmse_mnpc_effect.pdf', bbox_inches='tight')\n",
    "plt.show()\n",
    "\n",
    "print('Saved: rmse_noise_effect.pdf  |  rmse_mnpc_effect.pdf')\n",
]

new_cell = {
    "cell_type": "code",
    "execution_count": None,
    "metadata": {},
    "outputs": [],
    "source": PLOT_SOURCE,
}

nb["cells"].append(new_cell)

with open(nb_path, 'w', encoding='utf-8') as f:
    json.dump(nb, f, ensure_ascii=False, indent=1)

print(f"Done. Notebook now has {len(nb['cells'])} cells.")
